### ISSUE TITLE
invalid URL escape "%2F" ... failed to recover state of shard 

### ISSUE THREAD

**Issue by suntzu93** [celestiaorg/celestia-node#2067] opened 2023-04-13 07:58 UTC
### Celestia Node version

v0.8.2

### OS

Ubuntu 20.04.5 LTS

### Steps to reproduce it

Stop celestia bridge node :

`service celestia-bridge-node stop`

Start it :

`service celestia-bridge-node start`

### Expected result

Don't have these logs :

```
Apr 13 01:49:36 oenode celestia[1297702]: 2023-04-13T01:49:36.293+0200        WARN        dagstore        dagstore@v0.0.0-20230404123415-177451f83136/dagstore.go:572        failed to recover state of shard /3343E8F2AD37C1381B6F0C8A124422AD15CEBE4A28079A27CB89906BC0D07BF6: failed to parse mount URL: parse "fs://%2Froot%2F.celestia-bridge-blockspacerace-0%2Fblocks%2F3343E8F2AD37C1381B6F0C8A124422AD15CEBE4A28079A27CB89906BC0D07BF6": invalid URL escape "%2F"; skipping
Apr 13 01:49:36 oenode celestia[1297702]: 2023-04-13T01:49:36.293+0200        WARN        dagstore        dagstore@v0.0.0-20230404123415-177451f83136/dagstore.go:572        failed to recover state of shard /3345AAA5F8A9B39D8843EADAC59D0FB2696A5E986924C5F2453441A24F658396: failed to parse mount URL: parse "fs://%2Froot%2F.celestia-bridge-blockspacerace-0%2Fblocks%2F3345AAA5F8A9B39D8843EADAC59D0FB2696A5E986924C5F2453441A24F658396": invalid URL escape "%2F"; skipping
Apr 13 01:49:36 oenode celestia[1297702]: 2023-04-13T01:49:36.293+0200        WARN        dagstore        dagstore@v0.0.0-20230404123415-177451f83136/dagstore.go:572        failed to recover state of shard /33474162B2F8673783800853E3A81C78C65FC664F6D0AD1618A0BCEF3CE571B3: failed to parse mount URL: parse "fs://%2Froot%2F.celestia-bridge-blockspacerace-0%2Fblocks%2F33474162B2F8673783800853E3A81C78C65FC664F6D0AD1618A0BCEF3CE571B3": invalid URL escape "%2F"; skipping
Apr 13 01:49:36 oenode celestia[1297702]: 2023-04-13T01:49:36.293+0200        WARN        dagstore        dagstore@v0.0.0-20230404123415-177451f83136/dagstore.go:572        failed to recover state of shard /334844A327F8C12CA58C96C51AC5BAC9AED8B193F67C49C8B29A8C1FE2C67D96: failed to parse mount URL: parse "fs://%2Froot%2F.celestia-bridge-blockspacerace-0%2Fblocks%2F334844A327F8C12CA58C96C51AC5BAC9AED8B193F67C49C8B29A8C1FE2C67D96": invalid URL escape "%2F"; skipping
...
```

### Actual result

a lot of these logs

```
Apr 13 01:49:36 oenode celestia[1297702]: 2023-04-13T01:49:36.292+0200        WARN        dagstore        dagstore@v0.0.0-20230404123415-177451f83136/dagstore.go:572        failed to recover state of shard /333B6850F413F0A5C6FBA90BBFF383B2DCED0CB9560061D6874B11B101334A03: failed to parse mount URL: parse "fs://%2Froot%2F.celestia-bridge-blockspacerace-0%2Fblocks%2F333B6850F413F0A5C6FBA90BBFF383B2DCED0CB9560061D6874B11B101334A03": invalid URL escape "%2F"; skipping
Apr 13 01:49:36 oenode celestia[1297702]: 2023-04-13T01:49:36.293+0200        WARN        dagstore        dagstore@v0.0.0-20230404123415-177451f83136/dagstore.go:572        failed to recover state of shard /333F9B30013642B1E94835E244711CEF2B8847B49B2BDE67C3AE7B4C8B2F8349: failed to parse mount URL: parse "fs://%2Froot%2F.celestia-bridge-blockspacerace-0%2Fblocks%2F333F9B30013642B1E94835E244711CEF2B8847B49B2BDE67C3AE7B4C8B2F8349": invalid URL escape "%2F"; skipping
Apr 13 01:49:36 oenode celestia[1297702]: 2023-04-13T01:49:36.293+0200        WARN        dagstore        dagstore@v0.0.0-20230404123415-177451f83136/dagstore.go:572        failed to recover state of shard /3340506769F6E51A80ED38D0777384C35352673262D1614C5D74306C8E0077E6: failed to parse mount URL: parse "fs://%2Froot%2F.celestia-bridge-blockspacerace-0%2Fblocks%2F3340506769F6E51A80ED38D0777384C35352673262D1614C5D74306C8E0077E6": invalid URL escape "%2F"; skipping
Apr 13 01:49:36 oenode celestia[1297702]: 2023-04-13T01:49:36.293+0200        WARN        dagstore        dagstore@v0.0.0-20230404123415-177451f83136/dagstore.go:572        failed to recover state of shard /3340F8E7A50103CADC57DE27CCEF62F7FC146AF3A6754D94A06E14B01A673944: failed to parse mount URL: parse "fs://%2Froot%2F.celestia-bridge-blockspacerace-0%2Fblocks%2F3340F8E7A50103CADC57DE27CCEF62F7FC146AF3A6754D94A06E14B01A673944": invalid URL escape "%2F"; skipping
Apr 13 01:49:36 oenode celestia[1297702]: 2023-04-13T01:49:36.293+0200        WARN        dagstore        dagstore@v0.0.0-20230404123415-177451f83136/dagstore.go:572        failed to recover state of shard /334248F9829EABEC3B437EF32D094874FD7489FA456E1D5111170E2DBC1F527D: failed to parse mount URL: parse "fs://%2Froot%2F.celestia-bridge-blockspacerace-0%2Fblocks%2F334248F9829EABEC3B437EF32D094874FD7489FA456E1D5111170E2DBC1F527D": invalid URL escape "%2F"; skipping
Apr 13 01:49:36 oenode celestia[1297702]: 2023-04-13T01:49:36.293+0200        WARN        dagstore        dagstore@v0.0.0-20230404123415-177451f83136/dagstore.go:572        failed to recover state of shard /3342F5C22BC47787B486C65B8EBE4D92C3AE6DAA12BEF45938ECB74CDB2BD738: failed to parse mount URL: parse "fs://%2Froot%2F.celestia-bridge-blockspacerace-0%2Fblocks%2F3342F5C22BC47787B486C65B8EBE4D92C3AE6DAA12BEF45938ECB74CDB2BD738": invalid URL escape "%2F"; skipping
Apr 13 01:49:36 oenode celestia[1297702]: 2023-04-13T01:49:36.293+0200        WARN        dagstore        dagstore@v0.0.0-20230404123415-177451f83136/dagstore.go:572        failed to recover state of shard /3342FF82E3DCA6BA5EBEBF36F6241438D9F1200A196B3EDF0EB254D568FAD9F2: failed to parse mount URL: parse "fs://%2Froot%2F.celestia-bridge-blockspacerace-0%2Fblocks%2F3342FF82E3DCA6BA5EBEBF36F6241438D9F1200A196B3EDF0EB254D568FAD9F2": invalid URL escape "%2F"; skipping
Apr 13 01:49:36 oenode celestia[1297702]: 2023-04-13T01:49:36.293+0200        WARN        dagstore        dagstore@v0.0.0-20230404123415-177451f83136/dagstore.go:572        failed to recover state of shard /334365DAB7EAFF9D2CCAC0E293C38D9ECC74DB4E30B3CDA8294E165E7B72F144: failed to parse mount URL: parse "fs://%2Froot%2F.celestia-bridge-blockspacerace-0%2Fblocks%2F334365DAB7EAFF9D2CCAC0E293C38D9ECC74DB4E30B3CDA8294E165E7B72F144": invalid URL escape "%2F"; skipping
Apr 13 01:49:36 oenode celestia[1297702]: 2023-04-13T01:49:36.293+0200        WARN        dagstore        dagstore@v0.0.0-20230404123415-177451f83136/dagstore.go:572        failed to recover state of shard /334396F6473DD28ABB0BC81B19604CE184A1C649BD7E04C0FBA1058B091CECF5: failed to parse mount URL: parse "fs://%2Froot%2F.celestia-bridge-blockspacerace-0%2Fblocks%2F334396F6473DD28ABB0BC81B19604CE184A1C649BD7E04C0FBA1058B091CECF5": invalid URL escape "%2F"; skipping
Apr 13 01:49:36 oenode celestia[1297702]: 2023-04-13T01:49:36.293+0200        WARN        dagstore        dagstore@v0.0.0-20230404123415-177451f83136/dagstore.go:572        failed to recover state of shard /3343E8F2AD37C1381B6F0C8A124422AD15CEBE4A28079A27CB89906BC0D07BF6: failed to parse mount URL: parse "fs://%2Froot%2F.celestia-bridge-blockspacerace-0%2Fblocks%2F3343E8F2AD37C1381B6F0C8A124422AD15CEBE4A28079A27CB89906BC0D07BF6": invalid URL escape "%2F"; skipping
Apr 13 01:49:36 oenode celestia[1297702]: 2023-04-13T01:49:36.293+0200        WARN        dagstore        dagstore@v0.0.0-20230404123415-177451f83136/dagstore.go:572        failed to recover state of shard /3345AAA5F8A9B39D8843EADAC59D0FB2696A5E986924C5F2453441A24F658396: failed to parse mount URL: parse "fs://%2Froot%2F.celestia-bridge-blockspacerace-0%2Fblocks%2F3345AAA5F8A9B39D8843EADAC59D0FB2696A5E986924C5F2453441A24F658396": invalid URL escape "%2F"; skipping
Apr 13 01:49:36 oenode celestia[1297702]: 2023-04-13T01:49:36.293+0200        WARN        dagstore        dagstore@v0.0.0-20230404123415-177451f83136/dagstore.go:572        failed to recover state of shard /33474162B2F8673783800853E3A81C78C65FC664F6D0AD1618A0BCEF3CE571B3: failed to parse mount URL: parse "fs://%2Froot%2F.celestia-bridge-blockspacerace-0%2Fblocks%2F33474162B2F8673783800853E3A81C78C65FC664F6D0AD1618A0BCEF3CE571B3": invalid URL escape "%2F"; skipping
```

**Comment by distractedm1nd** [comment] 2023-04-13 09:18
Closing as duplicate of #2031
@suntzu93 , a fix is on the way :)

**Closed by distractedm1nd** 2023-04-13 09:18 UTC
Labels: bug, external
