### ISSUE TITLE
head request to trusted peer failed

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#2241] opened 2023-05-23 13:07 UTC
### Celestia Node version

v0.10.0

### OS

ubuntu

### Steps to reproduce it

https://github.com/celestiaorg/optimism/issues/57

### Expected result

No errors

### Actual result

errors in https://github.com/celestiaorg/optimism/issues/57

### Relevant log output

```bash
celestia-light-node | 2023-05-22T21:57:06.058Z  ERROR   header/p2p      p2p/exchange.go:144     head request to trusted peer failed     {"trustedPeer": "12D3KooWBtxdBzToQwnS4ySGpph9PtGmmjEyATkgX3PfhAo4xmf7", "err": "header/p2p: failed to open a new stream: context deadline exceeded"}
celestia-light-node | 2023-05-22T22:08:13.012Z  ERROR   header/p2p      p2p/exchange.go:144     head request to trusted peer failed     {"trustedPeer": "12D3KooWBtxdBzToQwnS4ySGpph9PtGmmjEyATkgX3PfhAo4xmf7", "err": "header/p2p: failed to open a new stream: context canceled"}
celestia-light-node | 2023-05-22T22:18:43.016Z  ERROR   header/p2p      p2p/exchange.go:144     head request to trusted peer failed     {"trustedPeer": "12D3KooWBtxdBzToQwnS4ySGpph9PtGmmjEyATkgX3PfhAo4xmf7", "err": "header/p2p: failed to open a new stream: context canceled"}
```

**Comment by Wondertan** [comment] 2023-05-24 14:42
Hey @jcstein. Which network were you running? The error suggests there is a peering problem and not a bug, so more information is needed to understand it.

**Comment by jcstein** [comment] 2023-05-24 15:46
hiya @Wondertan - Blockspace Race. let me know if you need anything else 🙏

**Comment by Wondertan** [comment] 2023-05-24 16:49
Does this happen consistently or was it only one run?

**Comment by jcstein** [comment] 2023-05-24 18:11
It starts and runs fine, mainly opened this to track this issue in case it is what is causing errors on the op stack testing we're doing. I think it's safe to close as we've narrowed in on [this](https://github.com/celestiaorg/celestia-app/issues/1816#issuecomment-1561382550) likely being the culprit

**Comment by jcstein** [comment] 2023-05-24 18:13
> Does this happen consistently or was it only one run?

it consistently happens on different runs, but is not consistent in the cadence of when it occurs

**Comment by Wondertan** [comment] 2023-05-24 18:32
Cool closing it then

**Closed** 2023-05-24 18:32 UTC
Labels: bug, external

**Comment by jcstein** [comment] 2023-05-24 18:34
sounds good. thanks for explaining the error more 🙏

**Comment by tuxcanfly** [comment] 2023-05-30 17:47
It seems that whenever this happens, requests timeout with:

`context deadline exceeded (Client.Timeout exceeded while awaiting headers`

Would it be possible for this to not block client requests? Due to this timeout, there's a cascade of failures eventually leading to the safe blocks not updating. Just flagging this, as it can be probably be worked around with long enough client timeouts.
