### ISSUE TITLE
das: Parallelise `catchUp` method

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#483] opened 2022-02-28 09:46 UTC
Supplement https://github.com/celestiaorg/celestia-node/pull/473 by additionally parallelising the DASing of past headers. 

TODOs mentioned [here](https://github.com/celestiaorg/celestia-node/pull/473#discussion_r828138649).

**Comment by renaynay** [comment] 2022-03-21 14:09
<img width="795" alt="Screenshot 2022-03-21 at 15 08 58" src="https://user-images.githubusercontent.com/41963722/159278716-9e18c92a-c645-42e0-b438-1cad483b0cf8.png">

**Comment by renaynay** [comment] 2022-06-28 12:33
Now that [DASState](#848) is almost implemented, we should consider the storing of errors for parallel `catchUp` workers whenever this issue is tackled.

**Comment by Bidon15** [comment] 2022-07-26 13:21
We should revisit https://github.com/celestiaorg/celestia-node/issues/504 and close it if after implementation of parallelisation, the issue is not reproducible again

**Closed** 2022-09-19 16:23 UTC
Labels: area:shares
