### ISSUE TITLE
unable to restart node on v0.11.0-rc7

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#2437] opened 2023-07-06 16:46 UTC
### Celestia Node version

v0.11.0-rc7

### OS

mac

### Install tools

docs

### Steps to reproduce it

1. [init node](https://app.warp.dev/block/PcyENsASa9zOxGE6a8PPsd)
2. [start node](https://app.warp.dev/block/Uk1hFoL2vPyGbPxx9h7Ra4) (stopped to save logs)
3. **unable to restart node** ([error logs](https://app.warp.dev/block/NPWPTfJhxBLfprFPb5LwIh))
4. [init new store](https://app.warp.dev/block/NPWPTfJhxBLfprFPb5LwIh)
5. [start logs](https://app.warp.dev/block/iPFjemLSOc8CcHSY7UFUGw)
6. check balance by going to https://0.0.0.0:26659/balance, and can reproduce "post failed: Post \"http://65.108.66.220:26657/\": dial tcp 65.108.66.220:26657: connect: connection refused" and then i get "header: not found"

### Expected result

node restarts

### Actual result

`Error: node: failed to start: error getting latest head during Start: header: not found`

### Relevant log output

```Shell
above in links
```

**Comment by lucadonnoh** [comment] 2023-07-11 19:47
same issue here

**Comment by renaynay** [comment] 2023-07-19 08:34
Cannot reproduce (and was likely a temporary issue with bootstrappers), closing.

**Closed by renaynay** 2023-07-19 08:34 UTC
Labels: bug, external
