### ISSUE TITLE
p2p connect fails

### ISSUE THREAD

**Issue by vlad2095** [celestiaorg/celestia-node#3534] opened 2024-06-27 11:42 UTC
### Summary of Bug

I am using  `ghcr.io/celestiaorg/celestia-node` container on MacOS M1.

While I tried to run light node in any of p2p network, it fails to connect via p2p
```
2024-06-18T06:08:16.254Z        INFO    node    nodebuilder/module.go:26        Accessing keyring...
2024-06-18T06:08:16.275Z        INFO    badger4 v4@v4.2.1-0.20240106094458-1c417aa3799c/levels.go:171   All 1 tables opened in 1ms

2024-06-18T06:08:16.276Z        INFO    badger4 v4@v4.2.1-0.20240106094458-1c417aa3799c/discard.go:66   Discard stats nextEmptySlot: 1

2024-06-18T06:08:16.276Z        INFO    badger4 v4@v4.2.1-0.20240106094458-1c417aa3799c/db.go:368       Set nextTxnTs to 143
2024-06-18T06:08:17.150Z        INFO    pidstore        pidstore/pidstore.go:67 Loaded peers from disk  {"amount": 0}
2024-06-18T06:08:17.150Z        INFO    module/header   header/config.go:66     No trusted peers in config, initializing with default bootstrappers as trusted peers
2024-06-18T06:08:17.170Z        INFO    header/p2p      p2p/subscriber.go:81    joining topic   {"topic ID": "/celestia/header-sub/v0.0.1"}
2024-06-18T06:08:17.170Z        INFO    header/p2p      p2p/exchange.go:99      client: starting client {"protocol ID": "/celestia/header-ex/v0.0.3"}
2024-06-18T06:08:17.170Z        INFO    pidstore        pidstore/pidstore.go:67 Loaded peers from disk  {"amount": 0}
2024-06-18T06:08:17.468Z        INFO    pidstore        pidstore/pidstore.go:84 Persisted peers successfully    {"amount": 0}
2024-06-18T06:08:17.468Z        WARN    header/p2p      p2p/subscriber.go:92    unregistering validator: no validator for topic /celestia/header-sub/v0.0.1
2024-06-18T06:08:17.468Z        INFO    basichost       basic/natmgr.go:112     DiscoverNAT error:no NAT found
2024-06-18T06:08:17.469Z        INFO    badger4 v4@v4.2.1-0.20240106094458-1c417aa3799c/db.go:546       Lifetime L0 stalled for: 0s

2024-06-18T06:08:17.476Z        INFO    badger4 v4@v4.2.1-0.20240106094458-1c417aa3799c/db.go:625       
Level 0 [ ]: NumTables: 00. Size: 0 B of 0 B. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 16 MiB
Level 1 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level 2 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level 3 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level 4 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level 5 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level 6 [B]: NumTables: 01. Size: 3.5 KiB of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level Done

Error: node: failed to start: header/p2p: failed to open a new stream: failed to dial: failed to dial 12D3KooWQpuTFELgsUypqp9N4a1rKBccmrmQVY8Em9yhqppTJcXf: all dials failed
  * [/ip4/163.172.132.189/tcp/2121] dial backoff
```
---

However, it seems like network-related issue, 'cause when I used mobile internet provider, it successfully started.
I remember having similar issue in one of my projects, where we solved it by increasing p2p timeout a bit.

Is it possible to configure celestia with increased p2p timeout or solve it in some other way?

### Version

Semantic version: v0.13.7
Commit: 0308aea76857ff27484946fce99004ebf10a3cb8
Build Date: Tue Jun 11 13:33:50 UTC 2024
System version: arm64/linux
Golang version: go1.22.3

### Steps to Reproduce

```
celestia light init --p2p.network celestia --core.ip rpc.celestia.pops.one
celestia light start --p2p.network celestia --core.ip rpc.celestia.pops.one
```

**Comment by Wondertan** [comment] 2024-06-27 14:14
Duplicate of #3533

**Closed by Wondertan** 2024-06-27 14:14 UTC
Labels: bug, external
