### ISSUE TITLE
Data Availability(Bad Encoding) Fraud Proofs

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-node#4] opened 2021-03-16 21:41 UTC
Another kind of fraud proofs that we need to implement, are data availability fraud proofs: nodes need to be able to generate proofs in case they observed an invalid erasure coding. 

Details are laid out in:
 - Section 5.5 of https://arxiv.org/pdf/1809.09044.pdf and
 - https://github.com/lazyledger/lazyledger-specs/blob/master/specs/data_structures.md#invalid-erasure-coding

Ideally, the implementation would be accompanied with a brief ADR.

Tasks
- [ ] Add BadEncodingFraudProof, [ShareProof](https://github.com/celestiaorg/celestia-specs/pull/190/files#diff-de87eed507b7afc65e81defcc06c4721cf9e4695820ec7976333dfa8945382cfR233-R243), and [NamespaceMerkleTreeInclusionProof](https://github.com/celestiaorg/celestia-specs/pull/190/files#diff-de87eed507b7afc65e81defcc06c4721cf9e4695820ec7976333dfa8945382cfR175-R186) protobuf messages.
- [ ] Add stubs in node to produce and verify BEFPs. (https://github.com/celestiaorg/celestia-node/issues/263)
- [ ] Implement local production and verification of BEFPs. (Draft implementation https://github.com/celestiaorg/celestia-core/pull/513)
- [ ] Implement passing around BEFPs in the network.
- [ ] Define node behavior ( #413)

**Comment by musalbas** [comment] 2021-12-14 18:16
Is this a duplicate of https://github.com/celestiaorg/celestia-core/issues/461?

**Comment by musalbas** [comment] 2021-12-14 18:44
Does this need adding to the testnet project board?

**Comment by liamsi** [comment] 2021-12-14 19:46
It already is (see to the right). But I just added it after I've closed the corresponding issue in core. 
Note that not all issues are yet properly triaged. But the testnet view (board) should actually be more or less conplete.

**Comment by renaynay** [comment] 2022-04-26 13:35
Closing in favour of https://github.com/celestiaorg/celestia-node/issues/528

**Closed by renaynay** 2022-04-26 13:35 UTC
