### ISSUE TITLE
[Feature Request]: publish prebuilt binaries from @celestiaorg

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#2411] opened 2023-06-29 04:42 UTC
### Implementation ideas

This would allow users and developers to download a prebuilt binary, published by @celestiaorg, for their machine. We could begin by publishing:
- arm64/darwin
- amd64/darwin
- arm64/linux
- amd64/linux

Providing precompiled binaries for commonly-used architectures would enhance the accessibility and distribution of Celestia Node. It simplifies the setup process by allowing users to download and run the binary without having to compile it from source or install any dependencies manually. This can be especially beneficial for users with less technical expertise or those running on systems with limited resources.

**Comment by jcstein** [comment] 2023-06-29 13:04
Can we do this for windows too? cc @MSevey i think you may have a trick up your sleeve
![image](https://github.com/celestiaorg/celestia-node/assets/46639943/b4c59ba2-dced-4d26-a4fd-a2a6d96a30bc)

**Comment by MSevey** [comment] 2023-06-30 02:21
> Can we do this for windows too? cc @MSevey i think you may have a trick up your sleeve

How other teams have done with is build the binaries in a docker container. This allows anyone to build the binaries and allows for reproducible builds. 

For example how Sia does it https://github.com/SiaFoundation/siad/tree/master/release-scripts

**Comment by jcstein** [comment] 2023-06-30 13:22
what about someone who wants to use the binary, but not use docker?

**Comment by jcstein** [comment] 2023-08-26 00:28
i think this would be useful so worth working into build pipelines

**Comment by jcstein** [comment] 2023-10-10 15:53
where are the binaries being published? i don't see them on the [latest release](https://github.com/celestiaorg/celestia-node/releases/tag/v0.11.0-rc15)

**Comment by ramin** [comment] 2023-10-10 16:20
@jcstein because that pipeline step is downstream from tests all passing, we have some flakey tests so the final bump and build binaries steps got skipped 😢 

@vgonkivs working on getting tests passing then this will behave and operate properly. I'll discuss with @MSevey what he wants process to be for back-filing these going forward if CI doesn't do it.

**Comment by jcstein** [comment] 2023-10-10 22:06
thank you for the context @ramin 🙌

**Comment by jcstein** [comment] 2023-10-25 20:41
Will this be live for the v0.12.0 release?

**Comment by jcstein** [comment] 2023-10-25 20:41
context: i am working on a prebuilt binary installation script for celestia-app. i would like to do the same for celestia-node

https://github.com/celestiaorg/docs/pull/1198

**Comment by ramin** [comment] 2023-10-25 20:47
Yes I’m working on testing signing as we speak, then will bypass what is blocking binary signing for tomorrow (Thurs)On Oct 25, 2023, at 4:41 PM, Josh Stein ***@***.***> wrote:﻿
context: i am working on a prebuilt binary installation script for celestia-app. i would like to do the same for celestia-node
celestiaorg/docs#1198

**Comment by ramin** [comment] 2023-12-12 10:08
@ramin ensure version bump is not relying on the failing/flakey tests and try this

**Comment by jcstein** [comment] 2024-02-21 13:50
here @Bidon15

**Comment by ramin** [comment] 2024-03-13 10:49
@jcstein https://github.com/celestiaorg/celestia-node/releases/tag/v0.13.1

There's a rare (not rate enough) case where the integrations tests fail, we just need to click re-run failed jobs on the pipeline/action and they pass and generate https://github.com/celestiaorg/celestia-node/actions/runs/8160543626/job/22604440899

Will be part of the checking on release. FINALLY

**Comment by jcstein** [comment] 2024-03-26 14:44
there were no prebuilt binaries published with v0.13.2 https://github.com/celestiaorg/celestia-node/releases/tag/v0.13.2
<img width="287" alt="Screenshot 2024-03-26 at 10 44 47 AM" src="https://github.com/celestiaorg/celestia-node/assets/46639943/f7d45f7c-353b-4e6d-ba10-4fba8ce1caf2">

**Comment by ramin** [comment] 2024-03-26 14:49
@jcstein the pipeline runs AFTER the release publishes and the action workflow is triggered,  they they get added at end of the workflow, so there will be a few minutes while it all gets built then added after

https://github.com/celestiaorg/celestia-node/actions/runs/8437846074

**Closed by ramin** 2024-03-26 14:49 UTC
Labels: enhancement, external, kind:ci
