### ISSUE TITLE
[Bug]: Redundant Logs for light clients

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#234] opened 2021-11-23 14:34 UTC
### Celestia Node version

a3bb430ebeaf946e5e92a87a05ea0aef4b888e04

### OS

macOS 12.0.1

### Install tools

make install

### Steps to reproduce it

1. Add a running celestia full node as a trusted peer for light client initialization
2. Start light client
3. Wait for 15-20 sec. for more logs in light client

### Expected result

Celestia light client is not duplicating logs info

### Actual result

Celestia light client is duplicating logs info

### Relevant log output

```shell
2021-11-23T15:26:59.251+0100	INFO	header-service	header/store.go:208	new head	{"height": 576, "hash": "FCF51ACF5AEFEC8E95C7E8B11CC34D923C1F025EAE754E86333A7F714EA4945A"}
2021-11-23T15:26:59.252+0100	INFO	header-service	header/store.go:208	new head	{"height": 576, "hash": "FCF51ACF5AEFEC8E95C7E8B11CC34D923C1F025EAE754E86333A7F714EA4945A"}
2021-11-23T15:26:59.252+0100	INFO	header-service	header/store.go:208	new head	{"height": 576, "hash": "FCF51ACF5AEFEC8E95C7E8B11CC34D923C1F025EAE754E86333A7F714EA4945A"}
2021-11-23T15:26:59.253+0100	INFO	header-service	header/store.go:208	new head	{"height": 576, "hash": "FCF51ACF5AEFEC8E95C7E8B11CC34D923C1F025EAE754E86333A7F714EA4945A"}
2021-11-23T15:26:59.253+0100	INFO	das	das/daser.go:89	sampling successful	{"height": 576, "hash": "FCF51ACF5AEFEC8E95C7E8B11CC34D923C1F025EAE754E86333A7F714EA4945A"}
2021-11-23T15:26:59.253+0100	INFO	das	das/daser.go:89	sampling successful	{"height": 576, "hash": "FCF51ACF5AEFEC8E95C7E8B11CC34D923C1F025EAE754E86333A7F714EA4945A"}
2021-11-23T15:26:59.253+0100	INFO	das	das/daser.go:89	sampling successful	{"height": 576, "hash": "FCF51ACF5AEFEC8E95C7E8B11CC34D923C1F025EAE754E86333A7F714EA4945A"}
2021-11-23T15:26:59.253+0100	INFO	das	das/daser.go:89	sampling successful	{"height": 576, "hash": "FCF51ACF5AEFEC8E95C7E8B11CC34D923C1F025EAE754E86333A7F714EA4945A"}
2021-11-23T15:26:59.306+0100	ERROR	header-service	header/store.go:189	invalid header	{"head": "FCF51ACF5AEFEC8E95C7E8B11CC34D923C1F025EAE754E86333A7F714EA4945A", "header": "FCF51ACF5AEFEC8E95C7E8B11CC34D923C1F025EAE754E86333A7F714EA4945A", "err": "headers must be adjacent in height"}
2021-11-23T15:26:59.306+0100	ERROR	header-service	header/sync.go:79	appending store with header from PubSub	{"hash": "FCF51ACF5AEFEC8E95C7E8B11CC34D923C1F025EAE754E86333A7F714EA4945A", "height": 576, "peer": "<peer.ID 12*7zLHGS>"}
2021-11-23T15:26:59.306+0100	ERROR	header-service	header/store.go:189	invalid header	{"head": "FCF51ACF5AEFEC8E95C7E8B11CC34D923C1F025EAE754E86333A7F714EA4945A", "header": "FCF51ACF5AEFEC8E95C7E8B11CC34D923C1F025EAE754E86333A7F714EA4945A", "err": "headers must be adjacent in height"}
2021-11-23T15:26:59.306+0100	ERROR	header-service	header/sync.go:79	appending store with header from PubSub	{"hash": "FCF51ACF5AEFEC8E95C7E8B11CC34D923C1F025EAE754E86333A7F714EA4945A", "height": 576, "peer": "<peer.ID 12*5wcWGQ>"}
```

**Comment by Wondertan** [comment] 2021-11-24 22:34
Duplicate of #237

**Closed by Wondertan** 2021-11-24 22:34 UTC
Labels: bug
