### ISSUE TITLE
[Bug]:  error logs in the light node

### ISSUE THREAD

**Issue by Semenovise** [celestiaorg/celestia-node#412] opened 2022-02-05 12:29 UTC
### Celestia Node version

v0.1.1

### OS

Ubuntu 20.04

### Steps to reproduce it

Installed and launched app node and full node on the same server, light client nstalled on a separate server.

### Expected result

Everything worked fine for a few days

### Actual result

Everything worked fine for a few days, but today I saw the error logs in the light node.
![Скриншот 05-02-2022 144259](https://user-images.githubusercontent.com/94569273/152641978-3af42f4a-238f-4389-b7f4-d4bf9652293e.jpg)

Restarting the light node helped.

![Скриншот 05-02-2022 144953](https://user-images.githubusercontent.com/94569273/152642047-c3a5feb5-81fd-4113-9289-9cc7095db289.jpg)

**Comment by Bidon15** [comment] 2022-08-09 13:43
Hi @Semenovise,
Thank you so much for the issue

We have reworked the logic so far and haven't witnessed these errors, yet. 
Please try our new `v0.3.0-rc2`. 

In addition, please feel free to reopen this issue if you bump into this behaviour again

**Comment by Bidon15** [comment] 2022-08-09 14:00
The root cause is lying in data not available and we will keep this issue opened as the reference for future issues with the same root causes
This should be fixed with discovery feature
In addition, we need to better formulate the error message

**Comment by renaynay** [comment] 2023-03-02 13:37
Closing as we're several minor versions down the line :) We will reopen an issue if we experience this problem with more relevant info.

**Closed by renaynay** 2023-03-02 13:37 UTC
Labels: bug
