### ISSUE TITLE
node: Define a Node Types/Modes

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#41] opened 2021-08-31 13:46 UTC
## Context
During sync discussions, we've touched upon the need for Nodes to differentiate peers by their Mode/Types. To accomplish this we need to concretely define those types.

## Implementation
```go 

// node.Type defines a type for Nodes to be differentiated.
type Type uint8

const (
	// node.Full is a full-featured Celestia Node.
	Full Type = iota + 1
	// node.Light is a stripped-down Celestia Node which aims to be lightweight while preserving highest possible
	// security guarantees.
	Light
)

// String converts Type to its string representation.
func (t Type) String() string {
	if !t.IsValid() {
		return "unknown"
	}
	return typeToString[t]
}

// IsValid reports whenever the Type is valid.
func (t Type) IsValid() bool {
	_, ok := typeToString[t]
	return ok
}

// typeToString keeps string representations of all valid Types.
var typeToString = map[Type]string{
	Full:  "Full",
	Light: "Light",
}

```

NOTE: Instead of Type there could be Mode

**Comment by Wondertan** [comment] 2021-09-02 11:09
@renaynay, regarding Type vs Mode.

The use of `Type` implies that some node Type is a concrete thing with a concrete set of functions and responsibilities, while `Mode` implies having one node type with different toggleable modes. 

Both make sense to me, but the issue here is that we've never discussed and defined the need for runtime switchability between modes, AFAIK. This is also why I liked the idea of having different binaries for different types and not one binary for all modes.

Before moving forward with this, we need to concretely decide this. Personally, I am ok with both but slightly inclined toward having both Types and Modes altogether(we would need Go plugins😸). Also, I don't like the fact that light nodes pull the whole codebase in binaries just for the ability to become a Full node. Can't think of this being a real case.

cc @musalbas as this seems pretty high-level.

**Comment by renaynay** [comment] 2021-09-02 13:01
I also want to cc @liamsi because this is something we discussed briefly at the offsite -- what would be nice is if we were to eventually move to a model where nodes could be "adaptive" in the network (so runtime switchability like you mentioned) and having two separate binaries, or separate binaries per node "type", would make that impossible. It would be cool if, for whatever reason, a node with more resources could go from Light -> Partial and if it encounters resource constraints, it could go from Partial -> Light, etc. This is obviously something that is way out of scope right now mainly bc 1. our networking stack would have to accommodate this kind of fluidity and 2. it's too much work for mainnet.

My understanding of a Celestia Node though (and what I think was pretty much confirmed during the offsite many times by @musalbas ) is that a Light node is just a Full node minus Block exchange/storage. I would then consider `Full` and `Light` to be two different "modes" of the Celestia Node, and I think it's totally fine to have one binary to support both. Eventually we will also have Partial nodes which are just `Full` nodes that store a specific block range(s). This is why the concept of `Services` on the node is so cool because you can just toggle them on / off depending on what kind of node it is.

I am in favour of `Mode`.

**Comment by renaynay** [comment] 2021-09-03 16:47
Wait i don't think this was resolved

**Comment by renaynay** [comment] 2021-11-29 15:52
For simplicity, @Wondertan and I decided on `Type`.

**Closed by renaynay** 2021-11-29 15:52 UTC
Labels: area:node
