### ISSUE TITLE
Add contribution guidlines & code of conduct

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-node#331] opened 2022-01-07 15:04 UTC
### Summary

Need contrib guidlines, release process docs, and code of conduct

### Impact on users

TODO: link related issues
inlcude release process #329 

### Cost of not doing

Confusion

### Evidence

TBD

### Implementation ideas

Re-use existing processes from the ecosystems we are already part of:
 - tendermint/Cosmos
 - IPFS/libp2p

### Urgency

High

**Comment by renaynay** [comment] 2022-04-26 14:58
Duplicate of https://github.com/celestiaorg/celestia-node/issues/75

Contribution guideline resolved by #391

**Closed by renaynay** 2022-04-26 14:58 UTC
Labels: enhancement
