### ISSUE TITLE
syncing over a header that's already been synced fails out for bridge nodes due to `shard already exists`

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#1784] opened 2023-02-20 14:37 UTC
```
2023-02-20T15:36:38.301+0100	ERROR	header/sync	sync/sync.go:214	syncing headers	{"from": 1025, "to": 25337, "err": "failed to initiate shard registration: 908B3B93B13FE69A682915F5E66B234BB7A95D7C34700110698BC620894529D6: shard already exists"}
```

This is failing because bridge node is trying to sync over a header that is already synced -- and since bridges extend and put during sync process, this error pops up and prevents further syncing.

**Comment by vgonkivs** [comment] 2023-02-20 15:01
The root cause: if our syncing process fails for some reason somewhere in the middle, then our syncer will not have the latest header but the eds store will.

**Comment by Wondertan** [comment] 2023-02-20 17:39
Duplicate of https://github.com/celestiaorg/celestia-node/issues/1785

**Closed by Wondertan** 2023-02-20 17:39 UTC
Labels: bug, area:header
