### ISSUE TITLE
[Bug]: "Can't deliver message to subscription...." in light-node LOGS

### ISSUE THREAD

**Issue by ddim77** [celestiaorg/celestia-node#408] opened 2022-02-01 09:12 UTC
### Celestia Node version

v0.1.1

### OS

Ubuntu 20.04

### Install tools

git clone + make install + create and run service

### Steps to reproduce it

Installed and launched the validator, full node and light client on the same server.
I used instructions from https://mzonder.notion.site/CELESTIA-8b8e89820d114c8cb9b6a63b377302ee (but an earlier version than now)

### Expected result

about 10 (or more) days the logs were fine

### Actual result

unusual logs in celestia light node

### Notes

A couple of weeks ago (or so) I installed a validator note, a little later I added a full node and a light client to the same server. Everything is going ok. But today I noticed the following logs in the light node:

![cel2](https://user-images.githubusercontent.com/28446928/151940269-7633c3f1-14c5-4ebc-b18e-1865dc537ce3.jpg)

Maybe it's some kind of bug, maybe not. In any case, I hope this information is useful. 
A simple restart of the light node helped to correct the situation.

**Comment by renaynay** [comment] 2022-02-01 11:57
Thank you so much for the report @ddim77 

Related https://github.com/celestiaorg/celestia-node/issues/402.

**Comment by Bidon15** [comment] 2022-08-09 13:58
The root cause is lying in data not available and we will keep this issue opened as the reference for future issues with the same root causes 
This should be fixed with discovery feature
In addition, we need to better formulate the error message

**Comment by Bidon15** [comment] 2022-08-09 14:01
Closing and ref to: https://github.com/celestiaorg/celestia-node/issues/412

**Closed by Bidon15** 2022-08-09 14:01 UTC
Labels: bug
