### ISSUE TITLE
client-nd: request status INTERNAL returned

### ISSUE THREAD

**Issue by vanphandinh** [celestiaorg/celestia-node#2051] opened 2023-04-11 15:05 UTC
### Celestia Node version

v0.8.2

### OS

Ubuntu 22.04.2 LTS

### Install tools

Docker

### Steps to reproduce it

1. Build the latest version of `celestia-node` docker image
2. Run a light node with the same key with my old bridge node
3. Build the latest version of `celestiaorg/ethermint` docker image
4. Run ethermint connected to the light node

### Expected result

No ERROR

### Actual result

2023-04-06T15:49:31.731Z        ERROR   shrex/nd        shrexnd/client.go:195   client-nd: request status INTERNAL returned
2023-04-06T15:49:34.790Z        ERROR   shrex/nd        shrexnd/client.go:195   client-nd: request status INTERNAL returned
![image](https://user-images.githubusercontent.com/13887599/231205624-e22c58a9-534f-4ebd-88f3-21e7e2c9b0bd.png)

### Notes

I still don't know how to reproduce this error again. A just note what I did.

**Comment by vanphandinh** [comment] 2023-04-11 15:18
I have found how to reproduce that bug.
![Screen Shot 2023-04-11 at 10 13 05 PM](https://user-images.githubusercontent.com/13887599/231209851-2270ee0e-5099-4e11-a50a-b8070627a72e.png)
![Screen Shot 2023-04-11 at 10 12 41 PM](https://user-images.githubusercontent.com/13887599/231209871-79a481d9-864d-4547-90a3-0f8e59a999c9.png)


When I tried to delete the ethermint container: `docker rm -f ethermint` and recreate it again with the same `NAMESPACE_ID` and `DA_BLOCK_HEIGHT`, that error occurred. If I recreate that container with the different `NAMESPACE_ID` and `DA_BLOCK_HEIGHT, there's nothing.

**Comment by jcstein** [comment] 2023-04-11 20:35
I'm seeing something similar, related to fetching data from the celestia light node, on my rollup:

``bash
4:33PM ERR failed to retrieve block from DALC daHeight=226223 errors="failed to retrieve block: Get \"http://localhost:26659/namespaced_data/b705585f236712ed/height/226223\": context deadline exceeded (Client.Timeout exceeded while awaiting headers); failed to retrieve block: Get \"http://localhost:26659/namespaced_data/b705585f236712ed/height/226223\": context deadline exceeded (Client.Timeout exceeded while awaiting headers); failed to retrieve block: Get \"http://localhost:26659/namespaced_data/b705585f236712ed/height/226223\": context deadline exceeded (Client.Timeout exceeded while awaiting headers); failed to retrieve block: Get \"http://localhost:26659/namespaced_data/b705585f236712ed/height/226223\": context deadline exceeded (Client.Timeout exceeded while awaiting headers); failed to retrieve block: Get \"http://localhost:26659/namespaced_data/b705585f236712ed/height/226223\": context deadline exceeded (Client.Timeout exceeded while awaiting headers); failed to retrieve block: Get \"http://localhost:26659/namespaced_data/b705585f236712ed/height/226223\": context deadline exceeded (Client.Timeout exceeded while awaiting headers); failed to retrieve block: Get \"http://localhost:26659/namespaced_data/b705585f236712ed/height/226223\": context deadline exceeded (Client.Timeout exceeded while awaiting headers); failed to retrieve block: Get \"http://localhost:26659/namespaced_data/b705585f236712ed/height/226223\": context deadline exceeded (Client.Timeout exceeded while awaiting headers); failed to retrieve block: Get \"http://localhost:26659/namespaced_data/b705585f236712ed/height/226223\": context deadline exceeded (Client.Timeout exceeded while awaiting headers); failed to retrieve block: Get \"http://localhost:26659/namespaced_data/b705585f236712ed/height/226223\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" module=BlockManager
```

**Comment by walldiss** [comment] 2023-04-21 10:30
Closing as duplicate of https://github.com/celestiaorg/celestia-node/issues/2044

**Closed by walldiss** 2023-04-21 10:30 UTC
Labels: bug, external
