### ISSUE TITLE
Error: node: failed to start: unexpected EOF

### ISSUE THREAD

**Issue by DasRasyo** [celestiaorg/celestia-node#3518] opened 2024-06-21 14:12 UTC
### Celestia Node version

v0.13.7

### OS

Ubuntu, 20.04- 22.04

### Install tools

makefiles

### Steps to reproduce it

This bug was introduced with the new update. Since the beginning of Mocha-4 network my node was working fine. After this update (v0.13.7) I saw the following in the logs;

celestia[2850189]: Level Done
celestia[2850189]: Error: node: failed to start: unexpected EOF

Then it restarts and got the same logs again.

The execstart line in the service file had the following: 

--keyring.accname my_celes_key \
--core.ip <IP> \
--core.rpc.port 26657 \
--core.grpc.port 9090 \
--p2p.network mocha\
--metrics.tls=true \
--metrics \
--metrics.endpoint otel.celestia-mocha.com 

I removed the default flags here. I left only --core.ip, --p2p.network and metric flags in the flags. And the problem was fixed, the node started working again. 

--core.ip <IP>:26657 --p2p.network mocha --metrics.tls=true --metrics --metrics.endpoint otel.celestia-mocha.com 

### Expected result

Node is expected to keep running

### Actual result

celestia[2850189]: Level Done
celestia[2850189]: Error: node: failed to start: unexpected EOF

### Relevant log output

```Shell
celestia[2850189]: Level Done
celestia[2850189]: Error: node: failed to start: unexpected EOF
```

### Notes

My mainnet bridge nodes were not affected. Only Testnet nodes were affected. Removing the flags I mentioned above from the startup line fixed the problem. 

Our conversations on Discord:
https://discordapp.com/channels/638338779505229824/920642717057421393/1253670566896861204

**Comment by eric-collazo** [comment] 2024-06-24 08:13
Hi! We had the same issue, and got solved changing the rpc from full.consensus.mocha-4.celestia-mocha.com to rpc-mocha.pops.one. No need to change any flags for us.

**Comment by renaynay** [comment] 2024-06-25 09:40
@DasRasyo and @eric-collazo can you please share some more logs prior to the EOF ?

**Comment by DasRasyo** [comment] 2024-06-25 16:42
@eric-collazo I didn't change RPC

@renaynay I cannot reproduce the same error now

**Comment by eric-collazo** [comment] 2024-06-26 05:53
Same for me, can't reproduce it anymore

**Comment by renaynay** [comment] 2024-06-27 09:25
awesome! closing for now. feel free to reopen if it happens again.

**Closed by renaynay** 2024-06-27 09:25 UTC
Labels: bug, external
