### ISSUE TITLE
High CPU Usage (95%+) in Celestia Mocha-4 Testnet Bridge Node v0.18.3-mocha (Shwap) with Wantlist Overflow

### ISSUE THREAD

**Issue by blacknodes** [celestiaorg/celestia-node#3904] opened 2024-10-30 15:22 UTC
### Celestia Node version

v0.18.3-mocha

### OS

Ubuntu 22.04.5 LTS

### Install tools

System version: amd64/linux  
Golang version: go1.23.2
Built binaries from sources!

### Steps to reproduce it

Running bridge node normally observing high CPU utilization
![image](https://github.com/user-attachments/assets/3d7d0ade-127b-45e7-a801-9466c9c3566b)

### Expected result

Node should maintain reasonable CPU usage without constant wantlist overflow messages.

### Actual result

- Consistent 95%+ CPU usage
- Frequent wantlist overflow messages in logs:
```
Oct 14 04:51:56 ubuntu celestia[2062926]: handling wantlist overflow {"local": "12D3KooWNMTSzUx34bS1VC6YbHVBbk6EorNjEsg4S8LVi5Z8uZVj", "from": "12D3KooWEwHk8gg7ArxcjEbzbtDGfRZx5ChmCX1fmCPxPEo3dAEf", "wantlistSize": 8045, "overflowSize": 51}
```

### Relevant log output

```Shell
Oct 11 07:07:33 ubuntu celestia[2062926]: 2024-10-11T07:07:33.495Z        INFO        bitswap/server/decision        decision/engine.go:727        handling wantlist overflow        {"local": "12D3KooWNMTSzUx34bS1VC6YbHVBbk6EorNjEsg4S8LVi5Z8uZVj", "from": "12D3KooWEwHk8gg7ArxcjEbzbtDGfRZx5ChmCX1fmCPxPEo3dAEf", "wantlistSize": 2, "overflowSize": 78}
Oct 11 07:07:41 ubuntu celestia[2062926]: 2024-10-11T07:07:41.667Z        INFO        bitswap/server/decision        decision/engine.go:727        handling wantlist overflow        {"local": "12D3KooWNMTSzUx34bS1VC6YbHVBbk6EorNjEsg4S8LVi5Z8uZVj", "from": "12D3KooWEwHk8gg7ArxcjEbzbtDGfRZx5ChmCX1fmCPxPEo3dAEf", "wantlistSize": 7997, "overflowSize": 99}
Oct 11 07:07:45 ubuntu celestia[2062926]: 2024-10-11T07:07:45.391Z        INFO        bitswap/server/decision        decision/engine.go:727        handling wantlist overflow        {"local": "12D3KooWNMTSzUx34bS1VC6YbHVBbk6EorNjEsg4S8LVi5Z8uZVj", "from": "12D3KooWEwHk8gg7ArxcjEbzbtDGfRZx5ChmCX1fmCPxPEo3dAEf", "wantlistSize": 7997, "overflowSize": 99}
Oct 11 07:07:49 ubuntu celestia[2062926]: 2024-10-11T07:07:49.329Z        INFO        bitswap/server/decision        decision/engine.go:727        handling wantlist overflow        {"local": "12D3KooWNMTSzUx34bS1VC6YbHVBbk6EorNjEsg4S8LVi5Z8uZVj", "from": "12D3KooWEwHk8gg7ArxcjEbzbtDGfRZx5ChmCX1fmCPxPEo3dAEf", "wantlistSize": 7997, "overflowSize": 99}
```

### Is the node "stuck"? Has it stopped syncing?

No, the Node just works fine!

### Notes

Node has been running for 23 days
Restarting node temporarily fixes high CPU usage but issue returns
Running on Mocha-4 testnet network

If needed, I can provide:

Extended log history
Network connectivity details
Node configuration files
Memory and CPU usage patterns over time

Please let me know what additional information would be helpful for debugging.

**Comment by Wondertan** [comment] 2024-10-30 15:48
Duplicate of https://github.com/celestiaorg/celestia-node/issues/3903

**Closed by Wondertan** 2024-10-30 15:48 UTC
Labels: bug, external
