### ISSUE TITLE
Mainnet celestia bridge reporting "Block cache might be too small"

### ISSUE THREAD

**Issue by rares-e2s** [celestiaorg/celestia-node#3009] opened 2023-12-14 15:07 UTC
### Celestia Node version

v0.12.1 Commit: b7b6350f8921d4454b8a38c8485d74f908fb6a61

### OS

Ubuntu 22.04.3 LTS

### Install tools

using systemd to run process. 
Using go1.21.3 to compile celestia bin

### Others

8 CPU & 32 GB RAM ubuntu VM. 

Systemd file: 

[Unit]
Description=celestia Bridge Node
After=network-online.target

[Service]
User=celestia-bridge
Group=celestia-bridge
ExecStart=/home/celestia-bridge/go/bin/celestia bridge start --p2p.network celestia \
        --gateway \
        --core.ip=a.b.c.d \
        --core.grpc.port=9090 \
        --metrics \
        --metrics.tls=false \
        --metrics.endpoint=otel-collector_IP&port

ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
RestartSec=3
LimitNOFILE=16384

[Install]
WantedBy=multi-user.target

### Steps to reproduce it

Run celestia bridge node on mainnet as per Celestia Docs

### Expected result

Warning logs not present

### Actual result

Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: 2023-12-10T09:02:06.987+0200        WARN        badger        v4@v4.0.0-20231125230536-2b9e13346f75/db.go:460        Block cache might be too small. Metrics: hit: 63609905 miss: 273534715 keys-added: 81233027 keys-updated: 1139187 keys-evicted: 81232863 cost-added: 8938313085214 cost-evicted: 8938045154777 sets-dropped: 3765 sets-rejected: 165791591 gets-dropped: 18176384 gets-kept: 318960960 gets-total: 337144620 hit-ratio: 0.19
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: 2023-12-10T09:02:06.987+0200        WARN        badger        v4@v4.0.0-20231125230536-2b9e13346f75/db.go:461        Cache life expectancy (in seconds):
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]:  -- Histogram:
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: Min value: 0
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: Max value: 11136
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: Count: 81228689
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: 50p: 2.00
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: 75p: 2.00
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: 90p: 8.00
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [0, 2) 67188389 82.72% 82.72%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [2, 4) 4150548 5.11% 87.82%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [4, 8) 3384036 4.17% 91.99%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [8, 16) 2467882 3.04% 95.03%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [16, 32) 1650346 2.03% 97.06%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [32, 64) 1073790 1.32% 98.38%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [64, 128) 734565 0.90% 99.29%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [128, 256) 433895 0.53% 99.82%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [256, 512) 122836 0.15% 99.97%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [512, 1024) 19389 0.02% 100.00%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [1024, 2048) 2418 0.00% 100.00%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [2048, 4096) 495 0.00% 100.00%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [4096, 8192) 98 0.00% 100.00%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [8192, 16384) 2 0.00% 100.00%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]:  --

### Relevant log output

```Shell
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: 2023-12-10T09:02:06.987+0200        WARN        badger        v4@v4.0.0-20231125230536-2b9e13346f75/db.go:460        Block cache might be too small. Metrics: hit: 63609905 miss: 273534715 keys-added: 81233027 keys-updated: 1139187 keys-evicted: 81232863 cost-added: 8938313085214 cost-evicted: 8938045154777 sets-dropped: 3765 sets-rejected: 165791591 gets-dropped: 18176384 gets-kept: 318960960 gets-total: 337144620 hit-ratio: 0.19
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: 2023-12-10T09:02:06.987+0200        WARN        badger        v4@v4.0.0-20231125230536-2b9e13346f75/db.go:461        Cache life expectancy (in seconds):
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]:  -- Histogram:
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: Min value: 0
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: Max value: 11136
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: Count: 81228689
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: 50p: 2.00
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: 75p: 2.00
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: 90p: 8.00
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [0, 2) 67188389 82.72% 82.72%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [2, 4) 4150548 5.11% 87.82%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [4, 8) 3384036 4.17% 91.99%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [8, 16) 2467882 3.04% 95.03%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [16, 32) 1650346 2.03% 97.06%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [32, 64) 1073790 1.32% 98.38%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [64, 128) 734565 0.90% 99.29%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [128, 256) 433895 0.53% 99.82%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [256, 512) 122836 0.15% 99.97%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [512, 1024) 19389 0.02% 100.00%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [1024, 2048) 2418 0.00% 100.00%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [2048, 4096) 495 0.00% 100.00%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [4096, 8192) 98 0.00% 100.00%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]: [8192, 16384) 2 0.00% 100.00%
Dec 10 09:02:06 rom247-celestia-bridge celestia[688792]:  --
```

**Comment by Wondertan** [comment] 2023-12-15 14:03
Hey @rares-e2s, its not a bug.This warning gets printed when there is a low cache hit rate in DB we use, which can happen in certain cases, so closing this.

Note for myself and other devs. This is coming from inverted index badger, as block cache was disabled on the general one

**Closed by Wondertan** 2023-12-15 14:03 UTC
Labels: bug, external

**Comment by rares-e2s** [comment] 2023-12-19 08:08
Thanks for your analysis , @Wondertan. 
Is this block cache configurable? I couldn't find something in config.toml file. 
I'm asking because we constantly get these warnings on our bridge on mainnet. 
Or should we just ignore the logs?

**Comment by Wondertan** [comment] 2024-01-22 20:47
You can ignore these logs for now. There is no way to increase the cache currently(https://github.com/celestiaorg/celestia-node/issues/2977)
