### ISSUE TITLE
Checksum mismatch when installing celestia-node

### ISSUE THREAD

**Issue by Ch1n3du** [celestiaorg/celestia-node#854] opened 2022-06-23 18:53 UTC
### Celestia Node version

0.3.0

### OS

linux (fedora)

### Install tools

Makefile

### Steps to reproduce it

- Clone the repo.
- Run `make install`.

### Expected result

Node should install

### Actual result

It errors out as the checksum for `rosetta-sdk-go@v0.7.8`'s checksum in the go.sum doesn't match that of the one downloaded.

### Relevant log output

```shell
$ make install
...
verifying github.com/coinbase/rosetta-sdk-go@v0.7.8: checksum mismatch
	downloaded: h1:omm1lMVE0CmF/7X+lQf19+VpTyALQdHdvbdfjnnfsNY=
	go.sum:     h1:op/O3/ZngTfcrZnp3p/TziRfKGdo7AUZGUmBu6+8qCc=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
make: *** [Makefile:25: install] Error 1
```

### Notes

I tried fixing it by changing the checksum in the go.sum but I'm not sure if this is a bigger issue.

**Comment by Wondertan** [comment] 2022-06-24 11:02
Hmm, we don't have `0.3.0` version, but `0.3.0-rc1`. Does this happen on main branch or on the tag?

**Comment by Ch1n3du** [comment] 2022-07-03 06:33
I didn't switch branches, just cloned the repo and ran make install, so it should be on main.

**Comment by Bidon15** [comment] 2022-08-09 13:21
Let's recheck this issue after we get the downgrade done and redo the steps

**Comment by Bidon15** [comment] 2022-08-23 14:21
Hey @Ch1n3du , I've tried make install and go-install and couldn't reproduce the original root cause
I'm closing the issue. Still feel free to open a new one if it reproduces for you 🙏

**Closed by Bidon15** 2022-08-23 14:21 UTC
Labels: bug
